In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Absenteeism_data.csv')

In [3]:
data.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

## Drop Id colunm

In [4]:
data = data.drop('ID', axis=1)

In [5]:
data.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [6]:
data.describe()

Reason for Absence  Transportation Expense  Distance to Work  \
count          700.000000              700.000000        700.000000   
mean            19.411429              222.347143         29.892857   
std              8.356292               66.312960         14.804446   
min              0.000000              118.000000          5.000000   
25%             13.000000              179.000000         16.000000   
50%             23.000000              225.000000         26.000000   
75%             27.000000              260.000000         50.000000   
max             28.000000              388.000000         52.000000   

              Age  Daily Work Load Average  Body Mass Index   Education  \
count  700.000000               700.000000       700.000000  700.000000   
mean    36.417143               271.801774        26.737143    1.282857   
std      6.379083                40.021804         4.254701    0.668090   
min     27.000000               205.917000        19.000000    1.000000   
25%     31.000000               241.476000        24.000000    1.000000   
50%     37.000000               264.249000        25.000000    1.000000   
75%     40.000000               294.217000        31.000000    1.000000   
max     58.000000               378.884000        38.000000    4.000000   

         Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000                 700.000000  
mean     1.021429    0.687143                   6.761429  
std      1.112215    1.166095                  12.670082  
min      0.000000    0.000000                   0.000000  
25%      0.000000    0.000000                   2.000000  
50%      1.000000    0.000000                   3.000000  
75%      2.000000    1.000000                   8.000000  
max      4.000000    8.000000                 120.000000

In [7]:
reason_dummies = pd.get_dummies(data['Reason for Absence'], drop_first=True)

In [8]:
reason_dummies = reason_dummies.astype(int)
reason_dummies.head()

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   

   26  27  28  
0   1   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 27 columns]

In [9]:
reason_1 = reason_dummies.loc[:, 1:14].max(axis=1)
reason_2 = reason_dummies.loc[:, 15:17].max(axis=1)
reason_3 = reason_dummies.loc[:, 18:21].max(axis=1)
reason_4 = reason_dummies.loc[:, 22:].max(axis=1)
reason_1

0      0
1      0
2      0
3      1
4      0
      ..
695    1
696    1
697    1
698    0
699    0
Length: 700, dtype: int32

In [10]:
data = data.drop('Reason for Absence', axis=1)

In [11]:
data = pd.concat([data, reason_1, reason_2, reason_3, reason_4], axis=1)

In [12]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [13]:
data.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [14]:
column = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1','Reason_2' , 'Reason_3', 'Reason_4']

In [15]:
data.columns = column

In [16]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

In [17]:
data['Date'] = pd.to_datetime(data['Date'], format='%d/%m/%Y')
data['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
         ...    
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, Length: 700, dtype: datetime64[ns]

In [18]:
data['Date'][0].month

7

In [19]:
list_month = []
for i in range(700):
    list_month.append(data['Date'][i].month)
list_month

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 

In [20]:
data['Month type'] = list_month

In [21]:
data.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  \
0                          4         0         0         0         1   
1                          0         0         0         0         0   
2                          2         0         0         0         1   
3                          4         1         0         0         0   
4                          2         0         0         0         1   

   Month type  
0           7  
1           7  
2           7  
3           7  
4           7

In [22]:
data_1 = data.copy()

In [23]:
def DOW(date_value):
    return date_value.weekday()

In [24]:
data_1['Day of the Week'] = data_1['Date'].apply(DOW)
data_1.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  \
0                          4         0         0         0         1   
1                          0         0         0         0         0   
2                          2         0         0         0         1   
3                          4         1         0         0         0   
4                          2         0         0         0         1   

   Month type  Day of the Week  
0           7                1  
1           7                1  
2           7                2  
3           7                3  
4           7                3

In [25]:
data_1['Education'] = data_1['Education'].map({1:0, 2:1, 3:1, 4:1})

In [26]:
data_1['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

In [27]:
data_1 = data_1.drop('Date', axis=1)

In [28]:
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month type', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']
data_1 = data_1[column_names_upd]

In [29]:
data_1.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month type  Day of the Week  \
0         0         0         0         1           7                1   
1         0         0         0         0           7                1   
2         0         0         0         1           7                2   
3         1         0         0         0           7                3   
4         0         0         0         1           7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [30]:
data_1.to_csv('Absenteeism_preprocessed.csv', index=False)

In [31]:
df = data_1

In [32]:
meadian = df['Absenteeism Time in Hours'].median()

In [33]:
meadian

3.0

In [34]:
import numpy as np
target = np.where(df['Absenteeism Time in Hours']> meadian, 1, 0)
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [35]:
df['Excessive Absentism'] = target

In [36]:
df.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month type  Day of the Week  \
0         0         0         0         1           7                1   
1         0         0         0         0           7                1   
2         0         0         0         1           7                2   
3         1         0         0         0           7                3   
4         0         0         0         1           7                3   
5         0         0         0         1           7                4   
6         0         0         0         1           7                4   
7         0         0         0         1           7                4   
8         0         0         1         0           7                0   
9         0         0         0         1           7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   
5               31          0         0     0                          2   
6               27          0         1     4                          8   
7               23          0         4     0                          4   
8               25          0         2     0                         40   
9               29          1         1     1                          8   

   Excessive Absentism  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0  
5                    0  
6                    1  
7                    1  
8                    1  
9                    1

In [37]:
df = df.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'], axis=1)

In [38]:
df = df.rename(columns={'Month type' : 'Month Value'})
df = df.rename(columns={'Pets' : 'Pet'})

In [39]:
inputs = df.iloc[:,:-1]

In [40]:
from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [41]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler()
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [42]:
inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [43]:
#columns_to_scale = ['Month type','Day of the Week', 'Transportation Expense', 'Distance to Work',
    # 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [44]:
# use list comprehension to iterate over the list
columns_to_scale = [x for x in inputs.columns.values if x not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pet']

In [45]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [46]:
absenteeism_scaler.fit(inputs)

C:\ProgramData\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'])

In [47]:

scaled_inputs = absenteeism_scaler.transform(inputs)

In [48]:
scaled_inputs.shape

(700, 11)

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
 target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [51]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, target, test_size=0.2, random_state=20)

In [52]:
x_train.shape

(560, 11)

In [53]:
y_train.shape

(560,)

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [55]:
reg = LogisticRegression()

In [56]:
reg.fit(x_train, y_train)

LogisticRegression()

In [57]:
reg.score(x_train, y_train)

0.7732142857142857

In [58]:
output = reg.predict(x_train)

In [59]:
output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [60]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [61]:
output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [62]:


np.sum(( output == y_train))

433

In [63]:
output.shape[0]

560

In [64]:
accu = np.sum(( output == y_train))/output.shape[0]
accu

0.7732142857142857

In [65]:
reg.intercept_

array([-1.6474549])

In [66]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [67]:
feature = inputs
feature_name = feature.columns.values

In [68]:
feature_df = pd.DataFrame(columns = ['feature_name'], data = feature_name)

In [69]:
feature_df

feature_name
0                 Reason_1
1                 Reason_2
2                 Reason_3
3                 Reason_4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                     Pet

In [70]:
feature_df['Coefficient'] = reg.coef_.T

In [71]:
feature_df.head()

feature_name  Coefficient
0     Reason_1     2.800197
1     Reason_2     0.951884
2     Reason_3     3.115553
3     Reason_4     0.839001
4  Month Value     0.158930

In [72]:
feature_df.index = feature_df.index + 1
feature_df.loc[0] = ['intercept', reg.intercept_[0]]
feature_df = feature_df.sort_index()
feature_df

feature_name  Coefficient
0                intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                     Pet    -0.277396

In [73]:
feature_df['Odd Ratio'] = np.exp(feature_df['Coefficient'])

In [74]:
feature_df = feature_df.sort_values('Odd Ratio', ascending=False)

In [75]:
feature_df

feature_name  Coefficient  Odd Ratio
3                 Reason_3     3.115553  22.545903
1                 Reason_1     2.800197  16.447892
2                 Reason_2     0.951884   2.590585
4                 Reason_4     0.839001   2.314054
6   Transportation Expense     0.605284   1.831773
10                Children     0.348262   1.416604
8          Body Mass Index     0.279811   1.322880
5              Month Value     0.158930   1.172256
7                      Age    -0.169891   0.843757
9                Education    -0.210533   0.810152
11                     Pet    -0.277396   0.757754
0                intercept    -1.647455   0.192539

In [76]:
reg.score(x_test,y_test)

0.75

In [77]:
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [78]:
predicted_proba.shape

(140, 2)

In [79]:
# import the relevant module
import pickle

In [80]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [81]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)